version: '3.7'

services:
  frontend:
    build:
      context: .
      args:
        NODE_ENV: "production"
        WIKI_LANG: "it"
        SDOW_API_URL: "https://api.seigradidiwikipedia.it"
    ports:
      - 8080:80
      
      